version: '3.10'
services:
  jupyterlab:
    container_name: 'jupyterlab'
    build: .
    env_file: ./docker.env
    volumes:
      - ./root_jupyter:/root/.jupyter
      - ./src:/usr/src
      - ./workspace:/workspace
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8080:8888"
